### PR TITLE
chore: upgrade deps

### LINKED ISSUE #286: Update deps
Would you accept a PR to update dependencies? In particular `sharp` to avoid [version mismatch issues](https://github.com/gatsbyjs/gatsby/issues/16957#issuecomment-536163039) with more up-to-date packages?

### PR DESCRIPTION
**Pull request by janosh**
Closes #286. In particular, bumps `sharp` to from 0.22.1 to 0.23.1

### CODE REVIEW

**Comment by janosh** [comment]
I got a lot of `gyp` errors when trying to update dependencies. Downgrading my `node` version I got `npx npm-check-updates -u` followed by `npm install` to work. However, that seems to cause issues with the `gulp` build task. Perhaps you guys can just update the deps at your end?

**Comment by evilebottnawi** [comment]
@janosh we need fix CI problems

**Comment by rturk** [comment]
Hi all. I'm confused what is blocking this?

**Comment by evilebottnawi** [comment]
@rturk failed CI

**Comment by janosh** [comment]
Do you know what the CI issue is? Can we help?

**Comment by JulianBerger** [comment]
Created a new Pull request which should fix the CI Issues: #290

**Comment by evilebottnawi** [comment]
Done

**Pull request closed without merging**
