### PR TITLE
Update dependencies, replace babel-preset-es2015 with babel-preset-env

### PR DESCRIPTION
**Pull request by rejas**

### CODE REVIEW

**Comment by rejas** [comment]
hi @evilebottnawi @cs-forever-ex @drabodan any feedback on this PR?

**Comment by brunocodutra** [comment]
@evilebottnawi I didn't even know this branch existed, I don't think I can review this PR.

**Comment by rejas** [comment]
hi @evilebottnawi @brunocodutra any news on this ?

**Comment by rejas** [comment]
In case you dont want to maintain this branch anymore, I'd be willing to take it over (would be nice to get the npm name for consistency sake)

**Comment by evilebottnawi** [comment]
@rejas oh, don't have time on this branch and better move this in separate repository, feel free to create repo `gulp-favicons` (and get the code from branch) and send me your npm nickname on sheo13666 @ gmail . com

**Comment by rejas** [comment]
@evilebottnawi done

**Comment by evilebottnawi** [comment]
@rejas sorry invalid email, use sheo13666q @ gmail . com

**Comment by rejas** [comment]
@evilebottnawi second try :-)

**Comment by evilebottnawi** [comment]
@rejas strange, no emails from you :confused:

**Comment by rejas** [comment]
Contrary to the first time no bounce email from my provider.... Maybe it landed in the spam? Otherwise you can write me at evilebottnawi @ veeck.de ;-)

**Comment by evilebottnawi** [comment]
@rejas done

**Comment by rejas** [comment]
Found your email in my spamfolder :-) replied!
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 27.12.18, 18:10, Evilebot Tnawi <notifications@github.com> schrieb:
@rejas done

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/itgalaxy/favicons","title":"itgalaxy/favicons","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/itgalaxy/favicons"}},"updates":{"snippets":[{"icon":"PERSON","message":"@evilebottnawi in #232: @rejas done"}],"action":{"name":"View Pull Request","url":"https://github.com/itgalaxy/favicons/pull/232#issuecomment-450193086"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/itgalaxy/favicons/pull/232#issuecomment-450193086",
"url": "https://github.com/itgalaxy/favicons/pull/232#issuecomment-450193086",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rejas** [comment]
Crated new repo and published updated version.

**Comment by evilebottnawi** [comment]
@rejas can you send a PR to README with link?

**Comment by rejas** [comment]
Hope the one I just created is sufficient?

**Pull request closed without merging**
