### PR TITLE
Added a "pixel art" mode which keeps pixels sharp

### PR DESCRIPTION
**Pull request by jameswilddev**
I'm working on something with a pixel art icon.  By default favicons uses what looks like some kind of cubic resize.  I've added a flag which preserves pixel art.

Flag unset:
Flag unset

Flag set:
Flag set

Thanks for this great tool!

### CODE REVIEW

**Comment by brunocodutra** [comment]
@jameswilddev this looks really reasonable, would you be willing to port this to the latest master?

Alternativelly, what about exposing a config option for the user to set custom flags for `image.contain`, this way we avoid the explosion of various boolean flags like your proposed `pixel_art`. What do you think?

// cc @evilebottnawi

**Comment by evilebottnawi** [comment]
hm, maybe, feel free to PR

**Comment by luislobo** [comment]
:+1: Any chance this can be merged in?

**Comment by luislobo** [comment]
BTW, this needs to be added to the README.md

**Comment by jameswilddev** [comment]
Just rebased.  Realized there's no tests for this.

**Comment by luislobo** [comment]
@jameswilddev Thanks for adding those! :)

**Pull request merged**
