### PR TITLE
Add CI GitHub action

### PR DESCRIPTION
**Pull request by andy128k**
- Changes in `.gitattributes` are needed for a prettier/eslint
- Nodejs 12 and 14 are supported. Nodejs 16 is not supported because of [broken fibers](https://github.com/laverdet/node-fibers). This may be done later.
- Actions "in action" are [here](https://github.com/andy128k/favicons/actions/runs/1351577034) :)

### CODE REVIEW

**Comment by alexander-akait** [comment]
@andy128k let's remove config for travis and appveyor, big thanks

**Comment by andy128k** [comment]
done

**Comment by alexander-akait** [comment]
@andy128k thanks

> Nodejs 12 and 14 are supported. Nodejs 16 is not supported because of broken fibers. This may be done later.

Will be great to fix it too

**Comment by andy128k** [comment]
Created a ticket #340 to not to forget about 16

**Pull request merged**
