### PR TITLE
Fixed vulnerabilities and updated Sharp to use latest version to support M1 mac build.

### PR DESCRIPTION
**Pull request by michtio**
Currently there is an issue on Mac M1 machines with an outdated version of libvips used by sharp, this issue is solved by updating sharp to `0.27.1` which uses the latest libvips `8.10.5` which has the fix for ARM architecture.

### CODE REVIEW

**Comment by michtio** [comment]
@alexander-akait I hope you can add this change quite quickly as a `6.2.1` release. Thank you :)

**Comment by alexander-akait** [comment]
Yep, let's wait CI green

**Comment by michtio** [comment]
@alexander-akait the CI has failed but on 

- doesn't support svg
- should be array notation


Both doesn't have to do anything with updated packages.

**Comment by alexander-akait** [comment]
Maybe you can update snapshots? Don't want to merge PR with broken tests...

**Comment by michtio** [comment]
@alexander-akait can you point me in the direction how to and I'll have a look to fix it :)

**Comment by alexander-akait** [comment]
`npm run test -- --update-snapshots` should work

**Comment by michtio** [comment]
Thank you will do those now

**Comment by michtio** [comment]
@alexander-akait want me to update version number / changelog as well?

**Comment by alexander-akait** [comment]
No need, I will update it before release

**Comment by michtio** [comment]
updating tests doesn't seem to fix anything @alexander-akait 

```
  1 tests were pending in test/svg.test.js

  ◌ svg › should support svg images

  1 test failed

  array › should accept an array of either buffers or paths to source images
  ```

**Comment by alexander-akait** [comment]
Okay, I will look at tests tomorrow

**Comment by michtio** [comment]
Thank you very much!

**Comment by michtio** [comment]
@alexander-akait did you have any luck with this?

**Comment by alexander-akait** [comment]
Updated, other packages was updated too, release will be today

**Comment by michtio** [comment]
Thank you very much :)

**Pull request closed without merging**
