### PR TITLE
Fix relative manifest paths

### PR DESCRIPTION
**Pull request by boba-keyost**
Option to remove `option.path` from sources in manifests.

### CODE REVIEW

**Comment by brunocodutra** [comment]
@boba-keyost firstly apologies for the really long delay reviewing this PR.

Your changes look sensible, could you just give a brief overview of your use-case?

**Comment by boba-keyost** [comment]
As I remember if I use base tag in HTML paths in manifests becomes unreachable.

**Comment by boba-keyost** [comment]
@evilebottnawi done

**Comment by boba-keyost** [comment]
@evilebottnawi  Sorry, updated test snapshot.

**Pull request merged**
