### PR TITLE
Added support for latest Apple Splash-Screens

### PR DESCRIPTION
**Pull request by methodev**
Added support for latest iOS Splash-Screens

* added support for splashscrens: iPhone 14 Pro, iPhone 15 Pro, iPhone 15, iPhone 14 Pro Max, iPhone 15 Pro Max, iPhone 15 Plus, 8.3” iPad Mini, 10.9” iPad Air

### CODE REVIEW

**Comment by andy128k** [comment]
@methodev New snapshot images are missing. You need to commit them too.

**Comment by methodev** [comment]
> @methodev New snapshot images are missing. You need to commit them too.

Done.

**Comment by mevbg** [comment]
Any plans to make a release soon? 🙂

**Comment by andy128k** [comment]
@mevbg  Published in 7.2.0

**Pull request merged**
