### PR TITLE
Replace all instances of new Buffer with Buffer.from

### PR DESCRIPTION
**Pull request by perrin4869**

### CODE REVIEW

**Comment by perrin4869** [comment]
Oh, #305 got squashed ><;;
It was rebased on this commit, so in reality these changes are already in master, closing

**Comment by perrin4869** [comment]
@evilebottnawi master should be ready for release. Not sure why, but the fail build seems to be caused by travis not being able to fetch the source code.

**Comment by perrin4869** [comment]
Hm... Well, regarding that one, it really isn't a breaking change as far as the documented usage was concerned in the `README.md`. If anyone was using the added `html` file using the normal API, they were relying on undocumented behavior, since passing the `pipeHTML` and `html` options was only demonstrated in the `stream` interface, and that was the original meaning of the options.
But of course it could break existing users, so I guess what I'm trying to say is, up to you :P

**Comment by perrin4869** [comment]
@evilebottnawi In my opinion, minor release with is the way to go here, unless you want to be totally safe. This release adds official `node@14` support, updates dependencies and some minor refactoring.

**Comment by evilebottnawi** [comment]
6.1.0 released

**Comment by evilebottnawi** [comment]
Thanks for help

**Pull request closed without merging**
