### PR TITLE
feat: Granularity in icons options

### PR DESCRIPTION
**Pull request by Voltra**
Add the ability to specify the exhaustive list of icons to generate per platform

### CODE REVIEW

**Comment by PhilippMeissner** [comment]
Any news on this one? Would love to see this implemented, currently we're generating a huge amount of images of which we only need like 4..

**Comment by perrin4869** [comment]
This looks good to me!!!!

**Comment by evilebottnawi** [comment]
@perrin4869 merge and release?

**Comment by perrin4869** [comment]
Go ahead :)

**Comment by evilebottnawi** [comment]
Thanks!

**Comment by PhilippMeissner** [comment]
@evilebottnawi @perrin4869 Will you also do a chore release today with these changes? :)

**Comment by evilebottnawi** [comment]
@PhilippMeissner Sorry for delay, many work :disappointed: Done https://github.com/itgalaxy/favicons/releases/tag/v6.2.0

**Comment by dmnsgn** [comment]
@Voltra does this also update the generated html? I don't see any change to `src/config/html.js`.

**Comment by Voltra** [comment]
@dmnsgn I must admit I was completely focused on the icon generation part and did not look that deeply into it. From what I saw this would probably mean a complete rework of the html rendering so this may be a task for a separate (but related) issue.

**Comment by evilebottnawi** [comment]
@Voltra Can you send a fix?

**Comment by Voltra** [comment]
I'm working on it, would have been easier if tests and generation did not rely on [hardcoded useless and incoherent whitespaces between HTML attributes](https://github.com/itgalaxy/favicons/blob/master/src/config/html.js#L49) (between 1 and 3). I should come up with a pull request pretty soon

**Pull request merged**
