### PR TITLE
Add node 14 support and upgrade sharp

### PR DESCRIPTION
**Pull request by perrin4869**
Upgrades sharp to `0.25`, which provides built binaries for node 14. Also travis tests in node 14.

### CODE REVIEW

**Comment by perrin4869** [comment]
Looks like we need to wait for a `node-canvas` release to provide prebuilt canvas binaries for node 14.

**Comment by perrin4869** [comment]
zbjornson was very kind to publish binaries for node@14, so now tests are passing :D

**Comment by perrin4869** [comment]
hm... Travis has no problem, but AppVeyor is complaining about snapshots not matching... could it be that in windows some of the updated libs work slightly different now? Any clues how to fix appveyor?

**Comment by evilebottnawi** [comment]
Oh, don't have idea, I think we need debug it, maybe bug on library side

**Comment by perrin4869** [comment]
Seems to be specific to converting of `test/fixtures/logo.svg`, although I don't know yet which of the generated resources is different.
But looking at the differences between the hex, it seems it is ever so slightly different, some `f`s turned into `e` or `d`s. I think getting to the bottom of this will be extremely convoluted

**Comment by perrin4869** [comment]
Examples of the very slight difference

**Comment by perrin4869** [comment]
@lovell I'm attempting to upgrade sharp here, but `0.25.0` seems to break the build on Windows. `sharp` is being used just to resize an `svg` buffer: https://github.com/itgalaxy/favicons/blob/9fa4945bfdc9aaebc60394464b4864f96eddae56/src/helpers.js#L276
Do you have any clues as to what the underlying cause might be?
Basically I could filter down the problem here to `svg -> ico` generation, on Windows the new `ico` is rendered slightly different. But `resemblejs` doesn't support `.ico` comparisons, so the snapshot is strictly compared.

**Comment by perrin4869** [comment]
@jamescryer @kghost @brunocodutra 
Looking at https://github.com/itgalaxy/favicons/blob/9fa4945bfdc9aaebc60394464b4864f96eddae56/test/Image.js#L44, you point out that `resemble.js` does not support comparing `.ico` images, but I did test `.ico` comparison and it seems to work just fine: 




For reference, here are the `.ico` files that I used to test:
[favicons.zip](https://github.com/itgalaxy/favicons/files/4602747/favicons.zip)

Do you have any insights as to why `.ico` testing was disabled by `resemble.js` here? It seems that without `resemble.js` comparison, slight differences in the generated `.ico` with `sharp@0.25` cause the tests to fail... only on windows, of course, lol

**Comment by perrin4869** [comment]
OK, so resemble.js doesn't support `.ico`  in node: https://github.com/Automattic/node-canvas/blob/2e9ea7377039f04290421bc751091a87ae8a0fa9/src/Image.cc#L339

I think the possible solutions are as follow:
1) Add .ico support to node-canvas (and therefore resemble.js)
2) Figure out why the `sharp@0.25.x` windows binaries are generating different results than the linux binaries
3) Have separate snapshots to test against in windows (should be possible, although I don't have much experience with ava)
4) Disables these checks in windows
5) write a custom, simple, naive compare function to compare `.ico` files

**Comment by perrin4869** [comment]
Done!!!!
Ended up implementing a separate comparator to `resemble.js` for the unsupported `.ico` files using [icojs](https://github.com/egy186/icojs) and [pixelmatch](https://github.com/mapbox/pixelmatch). Now small differences between ico files in the snapshots (below 5%) will allow the tests to still pass.
The snapshots have been updated to contain `Image` representations of the `.ico` files. `Image.prototype.compare` now handles `.ico` too.
Was a very good exercise!
@evilebottnawi please review again :)

**Comment by lovell** [comment]
@perrin4869 There are often very small rendering differences between platforms - sharp uses thresholding in all its unit tests as a consequence. In this case, given an ICO file usually contains uncompressed BMP data, you might also be able to convert the two Buffers to base64 strings then calculate the Hamming distance and verify against a threshold.

**Comment by perrin4869** [comment]
@lovell Thanks for the response!!!
Yup, this lib was also using thresholding for all other filetypes, but ico thresholding was missing.
If you got the time to look at it, is the solution that I implemented good enough, or are there any benefits from thresholding based on Hamming distance? I think the solution I implemented would work even if `.ico` contains png data :)
Up until `sharp@0.24.1`, converting svg to png would create the exact same result for Linux and Windows, but starting from `0.25.0`, very slight differences started to occur. Just out of curiosity, I was wondering what the root cause might be. I was thinking that maybe, the cause is slightly different build parameters are being used now? Or some patch being applied to Windows build? Or maybe upstream `libvips` implemented different rendering methods between the platforms?

**Comment by lovell** [comment]
@perrin4869 Feel free to open a new issue against sharp with sample images, code to reproduce, versions etc. https://github.com/lovell/sharp/issues/new?labels=question&template=question.md

**Comment by perrin4869** [comment]
@evilebottnawi This is ready for reviewing! The failed tests were apparently caused by a difference of options being passed to the `sharp` windows binaries at build time. But to get around that, I improved the tests to add threshold checks when comparing `.ico` files, which was missing from the previous tests (`.ico` files, and only `.ico`, were strictly compared due to a limitation of the lib used). This will make sure that the tests don't break in the future if the generated `.ico` files change by a small threshold.

**Comment by evilebottnawi** [comment]
@perrin4869 Something more? Should we do release?

**Comment by perrin4869** [comment]
Hm... maybe replace all calls to deprecated `new Buffer` with `Buffer.from` to avoid warnings, which is a trivial change would be nice. Can send another PR quickly for that

**Comment by perrin4869** [comment]
#308 will remove warnings when using the long deprecated `new Buffer`.
#305 would be a nice little refactor to sneak in, but no overall impact on usability

**Pull request merged**
