### PR TITLE
Added more icons form manifest and ios/windows #217

### PR DESCRIPTION
**Pull request by disjfa**
Also changed indentation of files.json to 2 spaces like all the rest. If you mind just let me know.

### CODE REVIEW

**Comment by disjfa** [comment]
Also, you can check this by adding my url https://disjfa.github.io/picalizer/ in the url input on https://www.pwabuilder.com

**Comment by disjfa** [comment]
I have no idea what the tests do, can anyone help me get on the way of those?

**Comment by brunocodutra** [comment]
@disjfa thanks for taking the time to put together this PR!

In principle your changes are pretty reasonable, however part of it exposes an underlying design flaw that needs some non trivial work to fix (see #202).

When Favicons was conceived, `manifest.json` was pretty much a chrome thing and as such it was designed so that it would only be generated if support for chrome is enabled in the configuration and hence it can only contain *chrome specific icons*. That means adding *apple specific icons* to `manifest.json` produces broken output, because if support for apple devices is disabled in the configuration the manifest links link to icons that don't actually exist.

First things first, let's merge the addition of `apple-touch-icon-1024x1024.png`. Could you revert the changes to the contents of `manifest.json`?

As to how tests are updated, you should run `npx ava -u test/**.test.js` from the project root then review and commit your changes.

**Comment by uwolfer** [comment]
@disjfa: Do you plan to update you PR? I would really welcome this change as it fixes most of pwabuilder.com warnings.

I have just tried your url with the current version of pwabuilder.com. It prints one (new?) warning:
> Missing image:
> A launch image of the following sizes is required: 750x1334, 1334x750, 1242x2208, 2208x1242, 640x1136, 640x960, 1536x2048, 2048x1536, 768x1024 and 1024x768 Platforms affected:ios.

**Pull request closed without merging**
