### PR TITLE
Add support for circle icons with drop shadow as often used on Android

### PR DESCRIPTION
**Pull request by uwolfer**
This change should be backward compatible.

The new circle icon style can be enabled with following config:

```js
  icons: {
    android: {
      background: true,
      mask: true,
      overlayShadow: true
    }
  }
```

This change changes some code parts where config is applied in order to
allow more config combinations. All options can now be applied on all
platforms. This is also the reason why background test snapshots have
been updated (background config option was ignored on windows in any case).

## Example
android-chrome-144x144

### CODE REVIEW

**Comment by uwolfer** [comment]
@brunocodutra: I have added a test - can you please verify that I've got it the right way? I have just created the test case and generated snapshots - I have no idea how to verify that the snapshots contain the expected content.

**Comment by uwolfer** [comment]
@brunocodutra: Do you find time to review this change in the next days?

**Comment by brunocodutra** [comment]
@uwolfer Sorry, I've been crazy busy the past couple of weeks.

**Comment by uwolfer** [comment]
@brunocodutra: Thank you for the review! Would be nice if you could push a new release of this lib and the webapp-webpack-plugin when you find time - but no hurry.

**Pull request merged**
