### PR TITLE
update sharp to 0.24.0

### PR DESCRIPTION
**Pull request by coulson84**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Thanks

**Comment by coulson84** [comment]
No problem. Do you update the npm package according to a schedule or is it ad hoc? Just wondering because the reason I bumped this dependency up is because sharp<0.24 fails to install on Mac running Node 13.6.0 which is currently a setup for one of our CI/CD machines.

Once this package is published I then also need to bump the favicons-webpack-plugin dependency on this package so trying to gauge how long things might take.

Thanks

**Comment by evilebottnawi** [comment]
@coulson84 I will do release tomorrow :+1:

**Comment by coulson84** [comment]
Thankyou 👍

**Pull request merged**
