### PR TITLE
Replace @babel/polyfill with core-js dependency

### PR DESCRIPTION
**Pull request by adipascu**
This is a fix for #225

### CODE REVIEW

**Comment by brunocodutra** [comment]
Looks good, but I wonder why `@babel-polyfil` doesn't work, any clue?

**Comment by adipascu** [comment]
@brunocodutra @babel/polyfill is not used, next time post a message before closing.

- Send from mobile

**Comment by brunocodutra** [comment]
You mean core-js alone would have been sufficient? I'm pretty sure I had people complaining about broken builds without @babel/polyfill before, but I could be wrong. Either way this should be harmless right?

**Comment by adipascu** [comment]
@brunocodutra Yes, core-js is suficient, polyfill is not currently used in the build bundle.

Extra depedencies might incur extra disk space/networking costs/cpu usage for some folks.

I am ok either way, just stating the reasoning behind my PR.

✌️Adrian

**Pull request closed without merging**
